// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTemplateToSessions(arg1, arg2) {
  return window['go']['main']['App']['ApplyTemplateToSessions'](arg1, arg2);
}

export function ClipboardRead() {
  return window['go']['main']['App']['ClipboardRead']();
}

export function ClipboardWrite(arg1) {
  return window['go']['main']['App']['ClipboardWrite'](arg1);
}

export function CloneSession(arg1) {
  return window['go']['main']['App']['CloneSession'](arg1);
}

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function ConnectTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectTab'](arg1, arg2, arg3, arg4);
}

export function CreateCommand(arg1) {
  return window['go']['main']['App']['CreateCommand'](arg1);
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function CreateTemplate(arg1) {
  return window['go']['main']['App']['CreateTemplate'](arg1);
}

export function DeleteBackgroundImage(arg1) {
  return window['go']['main']['App']['DeleteBackgroundImage'](arg1);
}

export function DeleteCommand(arg1) {
  return window['go']['main']['App']['DeleteCommand'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function DisconnectTab(arg1) {
  return window['go']['main']['App']['DisconnectTab'](arg1);
}

export function ExecuteBatch(arg1) {
  return window['go']['main']['App']['ExecuteBatch'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function ExportConfigWithOptions(arg1) {
  return window['go']['main']['App']['ExportConfigWithOptions'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBackgroundDir() {
  return window['go']['main']['App']['GetBackgroundDir']();
}

export function GetCommand(arg1) {
  return window['go']['main']['App']['GetCommand'](arg1);
}

export function GetConnectionInfo(arg1) {
  return window['go']['main']['App']['GetConnectionInfo'](arg1);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLogDir() {
  return window['go']['main']['App']['GetLogDir']();
}

export function GetLogList() {
  return window['go']['main']['App']['GetLogList']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetTabStatus(arg1) {
  return window['go']['main']['App']['GetTabStatus'](arg1);
}

export function GetTemplate(arg1) {
  return window['go']['main']['App']['GetTemplate'](arg1);
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function ImportConfigWithOptions(arg1, arg2) {
  return window['go']['main']['App']['ImportConfigWithOptions'](arg1, arg2);
}

export function ImportSecureCRTSessions(arg1) {
  return window['go']['main']['App']['ImportSecureCRTSessions'](arg1);
}

export function ListBackgroundImages() {
  return window['go']['main']['App']['ListBackgroundImages']();
}

export function ListCommands() {
  return window['go']['main']['App']['ListCommands']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListGroupsTree() {
  return window['go']['main']['App']['ListGroupsTree']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function LoadBackgroundImage(arg1) {
  return window['go']['main']['App']['LoadBackgroundImage'](arg1);
}

export function MkdirAll(arg1) {
  return window['go']['main']['App']['MkdirAll'](arg1);
}

export function MoveGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveGroup'](arg1, arg2);
}

export function NeedLocalEcho(arg1) {
  return window['go']['main']['App']['NeedLocalEcho'](arg1);
}

export function ParseSecureCRTFile(arg1) {
  return window['go']['main']['App']['ParseSecureCRTFile'](arg1);
}

export function PreviewImport(arg1) {
  return window['go']['main']['App']['PreviewImport'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function ReadFileString(arg1) {
  return window['go']['main']['App']['ReadFileString'](arg1);
}

export function ReadLogFile(arg1) {
  return window['go']['main']['App']['ReadLogFile'](arg1);
}

export function ResizeTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTab'](arg1, arg2, arg3);
}

export function SaveBackgroundImage(arg1, arg2) {
  return window['go']['main']['App']['SaveBackgroundImage'](arg1, arg2);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SearchCommands(arg1) {
  return window['go']['main']['App']['SearchCommands'](arg1);
}

export function SearchSessions(arg1) {
  return window['go']['main']['App']['SearchSessions'](arg1);
}

export function SelectDirectory(arg1, arg2) {
  return window['go']['main']['App']['SelectDirectory'](arg1, arg2);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2, arg3);
}

export function SelectFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFiles'](arg1, arg2, arg3);
}

export function SendToTab(arg1, arg2) {
  return window['go']['main']['App']['SendToTab'](arg1, arg2);
}

export function SendToTabBinary(arg1, arg2) {
  return window['go']['main']['App']['SendToTabBinary'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetLoggingEnabled(arg1) {
  return window['go']['main']['App']['SetLoggingEnabled'](arg1);
}

export function UpdateCommand(arg1) {
  return window['go']['main']['App']['UpdateCommand'](arg1);
}

export function UpdateGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2, arg3);
}

export function UpdateSession(arg1) {
  return window['go']['main']['App']['UpdateSession'](arg1);
}

export function UpdateTemplate(arg1) {
  return window['go']['main']['App']['UpdateTemplate'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsFullscreen() {
  return window['go']['main']['App']['WindowIsFullscreen']();
}

export function WindowIsMaximized() {
  return window['go']['main']['App']['WindowIsMaximized']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowToggleFullscreen() {
  return window['go']['main']['App']['WindowToggleFullscreen']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteFileString(arg1, arg2) {
  return window['go']['main']['App']['WriteFileString'](arg1, arg2);
}
