// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {command} from '../models';
import {version} from '../models';
import {logger} from '../models';
import {main} from '../models';

export function ApplyTemplateToSessions(arg1:string,arg2:Array<string>):Promise<void>;

export function ClipboardRead():Promise<string>;

export function ClipboardWrite(arg1:string):Promise<void>;

export function CloneSession(arg1:string):Promise<session.Session>;

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function ConnectTab(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function CreateCommand(arg1:command.Command):Promise<void>;

export function CreateGroup(arg1:string,arg2:string):Promise<session.Group>;

export function CreateSession(arg1:session.Session):Promise<void>;

export function CreateTemplate(arg1:session.PersonalizationTemplate):Promise<void>;

export function DeleteBackgroundImage(arg1:string):Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DisconnectTab(arg1:string):Promise<void>;

export function ExecuteBatch(arg1:command.ExecutionRequest):Promise<Array<command.ExecutionResult>>;

export function ExportConfig():Promise<string>;

export function ExportConfigWithOptions(arg1:boolean):Promise<string>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAppInfo():Promise<version.AppInfo>;

export function GetBackgroundDir():Promise<string>;

export function GetCommand(arg1:string):Promise<command.Command>;

export function GetConnectionInfo(arg1:string):Promise<Record<string, string>>;

export function GetHomeDir():Promise<string>;

export function GetLanguage():Promise<string>;

export function GetLogDir():Promise<string>;

export function GetLogList():Promise<Array<logger.LogFileInfo>>;

export function GetSession(arg1:string):Promise<session.Session>;

export function GetTabStatus(arg1:string):Promise<string>;

export function GetTemplate(arg1:string):Promise<session.PersonalizationTemplate>;

export function ImportConfig(arg1:string):Promise<void>;

export function ImportConfigWithOptions(arg1:string,arg2:main.ImportOptions):Promise<void>;

export function ImportSecureCRTSessions(arg1:Array<Record<string, any>>):Promise<void>;

export function ListBackgroundImages():Promise<Array<main.BackgroundFileInfo>>;

export function ListCommands():Promise<Array<command.Command>>;

export function ListFiles(arg1:string):Promise<Array<Record<string, any>>>;

export function ListGroups():Promise<Array<session.Group>>;

export function ListGroupsTree():Promise<Array<session.GroupNode>>;

export function ListSessions():Promise<Array<session.Session>>;

export function ListTemplates():Promise<Array<session.PersonalizationTemplate>>;

export function LoadBackgroundImage(arg1:string):Promise<string>;

export function MkdirAll(arg1:string):Promise<void>;

export function MoveGroup(arg1:string,arg2:string):Promise<void>;

export function NeedLocalEcho(arg1:string):Promise<boolean>;

export function ParseSecureCRTFile(arg1:string):Promise<main.SecureCRTParseResult>;

export function PreviewImport(arg1:string):Promise<main.ImportPreview>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadFileString(arg1:string):Promise<string>;

export function ReadLogFile(arg1:string):Promise<string>;

export function ResizeTab(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveBackgroundImage(arg1:string,arg2:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SearchCommands(arg1:string):Promise<Array<command.Command>>;

export function SearchSessions(arg1:string):Promise<Array<session.Session>>;

export function SelectDirectory(arg1:string,arg2:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectFiles(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function SendToTab(arg1:string,arg2:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetLoggingEnabled(arg1:boolean):Promise<void>;

export function UpdateCommand(arg1:command.Command):Promise<void>;

export function UpdateGroup(arg1:string,arg2:string,arg3:string):Promise<session.Group>;

export function UpdateSession(arg1:session.Session):Promise<void>;

export function UpdateTemplate(arg1:session.PersonalizationTemplate):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowIsFullscreen():Promise<boolean>;

export function WindowIsMaximized():Promise<boolean>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowToggleFullscreen():Promise<void>;

export function WriteFile(arg1:string,arg2:Array<number>):Promise<void>;

export function WriteFileString(arg1:string,arg2:string):Promise<void>;
